-- =============================================================================
-- Migration: 000006_seed_toefl_toeic_question_banks.sql
-- Description: Pure DDL Migration - All seed data removed
-- =============================================================================
